#!/usr/bin/env node
// Generated by openpond-agent-sdk. Current runtimes can call the CLI command in action-registry.json.
export const schema = "openpond.agent.runtime-bridge.v1";
export const actionRegistry = {
  "schemaVersion": 1,
  "schema": "openpond.agent.action-registry.v1",
  "generatedBy": "openpond-agent-sdk",
  "actions": [
    {
      "id": "chat",
      "name": "chat",
      "label": "Chat",
      "description": "Explain the Relay Cross-Chain Operator's explicit actions.",
      "command": "openpond-agent run chat",
      "target": {
        "kind": "intent-router",
        "router": "chat-router",
        "intents": [
          "relay_help"
        ],
        "defaultIntent": "relay_help"
      },
      "implementation": {
        "type": "intent-router",
        "routerId": "chat-router"
      },
      "visibility": "default",
      "timeoutSeconds": 60,
      "inputSchema": null,
      "outputSchema": null,
      "outputArtifacts": [],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Read-only action discovery."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "chat",
        "namespace": "actions"
      }
    },
    {
      "id": "quote-relay-transfer",
      "name": "quote-relay-transfer",
      "label": "Quote Relay Transfer",
      "description": "Request an unsigned exact-input EVM cross-chain quote through the Relay SDK.",
      "command": "openpond-agent run quote-relay-transfer",
      "target": {
        "kind": "workflow",
        "workflow": "quote-relay-transfer"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "quote-relay-transfer"
      },
      "visibility": "end_user",
      "timeoutSeconds": 180,
      "inputSchema": "RelayQuoteInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/relay-quote.json"
      ],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Read-only quote request without a wallet."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "quote-relay-transfer",
        "namespace": "actions"
      }
    },
    {
      "id": "review-relay-quote",
      "name": "review-relay-quote",
      "label": "Review Relay Quote",
      "description": "Verify and summarize a quote's hash, fees, steps, request IDs, and expiry.",
      "command": "openpond-agent run review-relay-quote",
      "target": {
        "kind": "workflow",
        "workflow": "review-relay-quote"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "review-relay-quote"
      },
      "visibility": "end_user",
      "timeoutSeconds": 60,
      "inputSchema": "RelayReviewInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/relay-quote-review.json"
      ],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Pure validation of a supplied quote artifact."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "review-relay-quote",
        "namespace": "actions"
      }
    },
    {
      "id": "relay-transfer-status",
      "name": "relay-transfer-status",
      "label": "Relay Transfer Status",
      "description": "Read cross-chain lifecycle state from Relay's status endpoint.",
      "command": "openpond-agent run relay-transfer-status",
      "target": {
        "kind": "workflow",
        "workflow": "relay-transfer-status"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "relay-transfer-status"
      },
      "visibility": "end_user",
      "timeoutSeconds": 120,
      "inputSchema": "RelayStatusInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/relay-status.json"
      ],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Read-only Relay API request."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "relay-transfer-status",
        "namespace": "actions"
      }
    },
    {
      "id": "broadcast-relay-step",
      "name": "broadcast-relay-step",
      "label": "Broadcast Relay Step",
      "description": "Verify, simulate, and broadcast one externally signed exact-match Relay transaction step.",
      "command": "openpond-agent run broadcast-relay-step",
      "target": {
        "kind": "workflow",
        "workflow": "broadcast-relay-step"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "broadcast-relay-step"
      },
      "visibility": "end_user",
      "timeoutSeconds": 600,
      "inputSchema": "RelayBroadcastInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/relay-step-receipt.json"
      ],
      "approvalPolicy": {
        "mode": "always",
        "reason": "Broadcasts a signed onchain transaction."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "broadcast-relay-step",
        "namespace": "actions"
      }
    }
  ]
};

export function commandForAction(name) {
  const action = actionRegistry.actions.find((candidate) => candidate.id === name || candidate.name === name);
  if (!action) throw new Error(`Unknown action: ${name}`);
  return action.command;
}
