#!/usr/bin/env node
// Generated by openpond-agent-sdk. Current runtimes can call the CLI command in action-registry.json.
export const schema = "openpond.agent.runtime-bridge.v1";
export const actionRegistry = {
  "schemaVersion": 1,
  "schema": "openpond.agent.action-registry.v1",
  "generatedBy": "openpond-agent-sdk",
  "actions": [
    {
      "id": "chat",
      "name": "chat",
      "label": "Chat",
      "description": "Explain the Safe Treasury Operator's explicit action surface.",
      "command": "openpond-agent run chat",
      "target": {
        "kind": "intent-router",
        "router": "chat-router",
        "intents": [
          "safe_help"
        ],
        "defaultIntent": "safe_help"
      },
      "implementation": {
        "type": "intent-router",
        "routerId": "chat-router"
      },
      "visibility": "default",
      "timeoutSeconds": 60,
      "inputSchema": null,
      "outputSchema": null,
      "outputArtifacts": [],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Read-only action discovery."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "chat",
        "namespace": "actions"
      }
    },
    {
      "id": "inspect-safe",
      "name": "inspect-safe",
      "label": "Inspect Safe",
      "description": "Read owners, threshold, nonce, modules, guard, version, and native balance from a deployed Safe.",
      "command": "openpond-agent run inspect-safe",
      "target": {
        "kind": "workflow",
        "workflow": "inspect-safe"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "inspect-safe"
      },
      "visibility": "end_user",
      "timeoutSeconds": 120,
      "inputSchema": "SafeInspectInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/safe-snapshot.json"
      ],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Read-only RPC calls."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "inspect-safe",
        "namespace": "actions"
      }
    },
    {
      "id": "build-safe-transaction",
      "name": "build-safe-transaction",
      "label": "Build Safe Transaction",
      "description": "Build an unsigned Safe transaction and canonical Safe transaction hash through Protocol Kit.",
      "command": "openpond-agent run build-safe-transaction",
      "target": {
        "kind": "workflow",
        "workflow": "build-safe-transaction"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "build-safe-transaction"
      },
      "visibility": "end_user",
      "timeoutSeconds": 180,
      "inputSchema": "SafeBuildInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/safe-transaction-plan.json"
      ],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Constructs an unsigned artifact without publishing it."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "build-safe-transaction",
        "namespace": "actions"
      }
    },
    {
      "id": "safe-transaction-status",
      "name": "safe-transaction-status",
      "label": "Safe Transaction Status",
      "description": "Read proposal, confirmation, and execution status from a Safe Transaction Service.",
      "command": "openpond-agent run safe-transaction-status",
      "target": {
        "kind": "workflow",
        "workflow": "safe-transaction-status"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "safe-transaction-status"
      },
      "visibility": "end_user",
      "timeoutSeconds": 120,
      "inputSchema": "SafeStatusInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/safe-transaction-status.json"
      ],
      "approvalPolicy": {
        "mode": "never",
        "reason": "Read-only Transaction Service request."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "safe-transaction-status",
        "namespace": "actions"
      }
    },
    {
      "id": "propose-safe-transaction",
      "name": "propose-safe-transaction",
      "label": "Propose Safe Transaction",
      "description": "Publish an externally signed and hash-verified Safe proposal; this does not execute it.",
      "command": "openpond-agent run propose-safe-transaction",
      "target": {
        "kind": "workflow",
        "workflow": "propose-safe-transaction"
      },
      "implementation": {
        "type": "workflow",
        "workflowId": "propose-safe-transaction"
      },
      "visibility": "end_user",
      "timeoutSeconds": 180,
      "inputSchema": "SafeProposeInput",
      "outputSchema": null,
      "outputArtifacts": [
        "artifacts/safe-proposal-receipt.json"
      ],
      "approvalPolicy": {
        "mode": "always",
        "reason": "Publishes a signed proposal to a Safe Transaction Service."
      },
      "setupRequirements": [],
      "mcp": {
        "enabled": false
      },
      "trace": {
        "name": "propose-safe-transaction",
        "namespace": "actions"
      }
    }
  ]
};

export function commandForAction(name) {
  const action = actionRegistry.actions.find((candidate) => candidate.id === name || candidate.name === name);
  if (!action) throw new Error(`Unknown action: ${name}`);
  return action.command;
}
